In [5]:
%pip install --upgrade pip --quiet
%pip install numpy --quiet

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [7]:
import random
import numpy as np

In [27]:
population_size = 5
N = 20
num_generations = 10
mutation_rate = 0.01

# Función para generar una población inicial
def generate_population(pop_size, num_assets):
    return [ np.random.dirichlet(np.ones(num_assets), size=1)[0] for _ in range(pop_size)]

In [28]:
generate_population(population_size, N)

[array([0.06205531, 0.15607188, 0.02206275, 0.03673279, 0.00457942,
        0.02439323, 0.06730759, 0.02612592, 0.02176624, 0.03308615,
        0.01767705, 0.01942021, 0.07441034, 0.03248616, 0.0228129 ,
        0.06889369, 0.12881749, 0.07701701, 0.08472213, 0.01956174]),
 array([0.22370779, 0.00865258, 0.02042592, 0.0092873 , 0.00543216,
        0.14823077, 0.10458949, 0.05070392, 0.08660035, 0.0066658 ,
        0.09190751, 0.02706383, 0.00344701, 0.01832385, 0.0050892 ,
        0.0804783 , 0.02216659, 0.03293048, 0.0262987 , 0.02799846]),
 array([0.00274972, 0.01953747, 0.117988  , 0.05486906, 0.14210091,
        0.01009403, 0.05769964, 0.00982466, 0.00811545, 0.04963091,
        0.01795168, 0.02703119, 0.0105814 , 0.03016828, 0.03298731,
        0.01313019, 0.10710759, 0.13120227, 0.11783512, 0.03939512]),
 array([0.0093951 , 0.01113828, 0.03418815, 0.04192035, 0.00273892,
        0.00716019, 0.18765576, 0.02005538, 0.0189945 , 0.01851657,
        0.04110065, 0.05228154, 0.2256655 